name: Internal Tasks
description: "Tasks related to introducing new configuration variables"
title: "INTT: "
assignees: ["badal773"]
projects: ["devtron-labs/6"]
labels: ["INTERNAL"]
body:
  - type: dropdown
    attributes:
      label: checking if there is any change 
      description: if there is any config or secret introduced
      options:
        - NO
        - ONLY CONFIG
        - ONLY SECRETS
        - BOTH CONFIG & SECRETS
    validations:
      required: true
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
  - type: textarea
    id: NewConfigurationUnification
    validations:
      required: false
    attributes:
      label: "New Configuration Unification"
      render: yaml
      description: "Intended for all who are introducing new configuration variables, flags, or secrets in microservices."
      value: |
              microservices:
              - name: orchestrator
                configs:
                  - key: DUMMY_KEY_ENABLED
                    allowedValues:
                      - true
                      - false
                    defaultValue: true
                    description: Flag to enable the buildx feature
                secrets:
                  - key: GITHUB_TOKEN
                    allowedValues:
                      - Github token only
                    defaultValue: "NULL"
                    description: Github token to fetch code during build time
