name: Internal Tasks
description: "Tasks related to introducing new configuration variables"
title: "INTT: "
assignees: ["badal773"]
projects: ["devtron-labs/6"]
labels: ["INTERNAL"]
body:
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
  - type: textarea
    id: NewConfigurationUnification
    validations:
      required: false
    attributes:
      label: "New Configuration Unification"
      render: yaml
      description: "Intended for all who are introducing new configuration variables, flags, or secrets in microservices."
      placeholder: |
              microservices:
                  - name: orchestrator
                    configs:
                      -     key: FEATURE_BUILDX_ENABLED
                            allowedValues:
                              - true
                              - false
                            defaultValue: true
                            description: Flag to enable the buildx feature
                    secrets:
                      -     key: GITHUB_TOKEN
                            allowedValues:
                              - Github token only
                            defaultValue: "NULL"
                            description: Github token to fetch code during build time
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Example: Whenever I visit the personal account page (1-2 times a week)"
    validations:
      required: true
