name: Internal Tasks
description: "Template for tasks related to the introduction of new configuration variables, flags, or secrets in microservices."
title: "INTT: "
assignees: ["badal773"]
projects: ["devtron-labs/6"]
labels: ["INTERNAL", "CONFIGURATION", "SECRETS"]

body:
  - type: dropdown
    attributes:
      label: "Configuration and Secret Changes"
      description: "Select the type of change being introduced: configuration, secrets, or both."
      options:
        - "Configuration Only"
        - "Secrets Only"
        - "Both Configuration and Secrets"
    validations:
      required: true

  - type: textarea
    id: NewConfigurationDetails
    validations:
      required: false
    attributes:
      label: "New Configuration and Secret Details"
      render: yaml
      description: "Provide details for new configuration variables, flags, or secrets introduced within the microservices. Include details such as allowed values, default values, and descriptions for clarity."
      value: |
        microservices:
          - name: orchestrator
            config:
              - key: DUMMY_KEY_ENABLED
                allowedValues:
                  - true
                  - false
                defaultValue: true
                description: "Enables or disables the dummy feature."
            secrets:
              - key: DUMMY_TOKEN
                allowedValues:
                  - "Token only"
                defaultValue: "NULL"
                description: "Token used to authenticate code fetch during build time."
