name: Internal Tasks
description: "Tasks related to internal activities"
title: "INTT: "
assignees: ["badal773"]
projects: ["devtron-labs/6"]
labels: ["INTERNAL"]
body:
  - type: dropdown
    id: task-type
    attributes:
      label: Task type
      description: Which type of task is this
      options:
        - Devtron Product
        - Cleanup
        - Developers queries
        - QA queries
        - Security
        - Compliances
        - Installer
        - Releases
        - Automation
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
  - type: textarea
    id: NewConfigurationUnification
    validations:
      required: false
    attributes:
      label: " New Configuration Unification"
      description: "Intended for all who are introducing new configuration variables, flags, or secrets in microservices."
      placeholder: |
              microservices:
                  - name: orchestrator
                    configs:
                      -     key: FEATURE_BUILDX_ENABLED
                            allowedValues:
                              - true
                              - false
                            defaultValue: true
                            description: Flag to enable the buildx feature
                    secrets:
                      -     key: GITHUB_TOKEN
                            allowedValues:
                              - Github token only
                            defaultValue: "NULL"
                            description: Github token to fetch code during build time


  - type: textarea
    id: task-description
    validations:
      required: true
    attributes:
      label: "Task description"
      description: "A clear and concise description of what the task is."
      placeholder: "You should add ..."
  - type: textarea
    id: tasklist
    validations:
      required: false
    attributes:
      label: "Subtask (If any)"
      description: "A clear list of sub-tasks if any. The list items may contain the link to other github issues or just the text."
      placeholder: "- [ ]  https://github.com/devtron-labs/devtron/issues/4482 (Sub-task link, the sub task is automatically marked completed when the issue is closed )"